### ISSUE TITLE
npm package name: rchain? rchain-api?

### ISSUE THREAD

**Issue by dckc** [JoshOrndorff/RChain-API#22]
In #19, @crypto-coder suggests `npm install --save rchain`. @JoshOrndorff says he likes it.

Hmm... it seems like a land-grab, to me; are we really developing *the* rchain module?

Not that `rchain-api` was any less of a land-grab. Hmm...

**Comment by JoshOrndorff** [comment]
I think we're developing _the_ rchain module for javascript. Taking that name doesn't preclude development of `rchain.py` or `rchain.java`. We could even pronounce the project "RChain JS".

The one situation I can imagine making me regret the land-grab is if someone wants to develop the actual node in javascript. But I think js would be pretty far down the list preferred languages for that.

**Comment by JoshOrndorff** [comment]
Although I'm certainly open to suggestions @dckc if you have something you like more.

**Comment by JoshOrndorff** [comment]
panthR

**Comment by JoshOrndorff** [comment]
This issue was moved to rchain/rchain-api#4
