### ISSUE TITLE
Document ocap style

### ISSUE THREAD

**Issue by JoshOrndorff** [JoshOrndorff/RChain-API#23]
Many familiar with javascript are used to ambient authority. Documenting our ocap style in CONTRIBUTING.md will help.

**Comment by JoshOrndorff** [comment]
How'd I do @dckc? 2e36be1f274820c724

**Comment by dckc** [comment]
It's a good start, but it's not quite clear on why we pass in gRPC but not, say, the string slice function. (answer: slice is deterministic, but gRPC is not; results of calls to it depend on more than just the inputs; results depend on the state of the network). I think that's a critical distinction, so I'm re-opening this.

My most recent attempt was this:

https://github.com/dckc/rchain-dbr/blob/master/CONTRIBUTING.md#object-capability-ocap-discipline

**Comment by JoshOrndorff** [comment]
Kamino closed and cloned this issue to [rchain/rchain-api](https://github.com/rchain/rchain-api/issues/2)

**Comment by JoshOrndorff** [comment]
Moved to https://github.com/rchain/rchain-api/issues/2
