### ISSUE TITLE
move repo to rchain org?

### ISSUE THREAD

**Issue by dckc** [JoshOrndorff/RChain-API#25]
We now have 3 active collaborators. Is it time to move to the https://github.com/rchain organization? 

Unlike commits, which are fully decentralized and completely portable across forks / users / organizations, issues are closely associated with their repo.

see also https://github.com/JoshOrndorff/RChain-Status/issues/6

**Comment by dckc** [comment]
Merging the python work in later looks awkward. Doing it now is awkward too (moving stuff in git is iffy and moving files/directories in github breaks web links), but not as as bad as saying "rchain/panthR is js" and later trying to re-define it as "panthR is rchain clients for lots of languages". So the choices that look acceptable to me are:

  - js-only repo: panthR (other names are probably fine too)
  - multi-language repo: rchain-client

I'd rather not do rchain/rchain. But maybe we should ask @MParlikar or @KentShikama

**Comment by JoshOrndorff** [comment]
Medha just pointed out https://github.com/rchain/JSAPI

If we were worried about RChain-API being a land grab, JSAPI is surely worse. I guess the fact that it lives under the rchain org helps, but not with npm packaging. I think getting the repo created was the hard part. Changing the name should be no problem.

I think the last blocker is whether python code lives there with us. Paging @pdonorio

**Comment by JoshOrndorff** [comment]
Other python work from proof team https://github.com/proof-media/rchain-grpc

**Comment by pdonorio** [comment]
I'm ok with changing name and having folders for languages there.

We'd love to merge our python code with yours there under `python` and help going maintaining / going forward.

The repo above was our first step to get the code out from our private repos :)

**Comment by dckc** [comment]
FWIW: npm looks in `package.json`, not at the repo name, for the package name. no way we'd use JSAPI as an npm package name, but qualified as rchain/JSAPI, it's not as big of a land-grab as a repo name. Still... something python-friendly like rchain-client or rnode-client would be my preference.

**Comment by JoshOrndorff** [comment]
Also tracked in https://rchain.atlassian.net/browse/OPS-330

**Comment by JoshOrndorff** [comment]
Seems like the last blocker is name. What was wrong with keeping RChain-API? That's python friendly.

**Comment by dckc** [comment]
I'm not a fan of mixed-case, but I can live with it.

**Comment by pdonorio** [comment]
I'm ok with any name that doesn't use JS or Python in it :) 
But to be fair `rchain-api` seems more like a github name to me

**Comment by JoshOrndorff** [comment]
I'm fine with all lower case, let's do that.

> rchain-api seems more like a github name to me

You mean that's a good name for a github repo but not a npm/pypi package?

**Comment by pdonorio** [comment]
It might fit well also for a pypi package, not sure about npm

**Comment by JoshOrndorff** [comment]
I motion to move forward with `rchain-api`. Anyone opposed?

**Comment by pdonorio** [comment]
Nope

**Comment by JoshOrndorff** [comment]
We're all moved in to github.com/rchain/rchain-api

I'm closing this and we can open new issues for follow-up as necessary.
