### ISSUE TITLE
Implement listenForContinuationAtName

### ISSUE THREAD

**Issue by JoshOrndorff** [JoshOrndorff/RChain-API#4]
RNode [offers a service](https://github.com/JoshOrndorff/RChain-API/blob/master/protobuf/CasperMessage.proto#L15) to check for continuations on a name, that this API does not expose.

Ultimately I'd like to support the entire gRPC API to the extent possible. The implementation should be similar to the one for [listenForDataAtName](https://github.com/JoshOrndorff/RChain-API/blob/master/rnodeAPI.js#L96-L113)

**Comment by dckc** [comment]
I'm not that interested to support it just because it's there. But you thought of a use case, didn't you, @JoshOrndorff ?

**Comment by JoshOrndorff** [comment]
I thought of two, but only remember one right now.

It would be nice for dApp UIs to automatically  prevent users from trying to call contracts that don't exist. For example trying to be the 10th caller to a radio station that isn't having such a competition. Or posting their status before they registered.

**Comment by JoshOrndorff** [comment]
This issue was moved to rchain/rchain-api#11
