### ISSUE TITLE
Support listening on unforgeable names

### ISSUE THREAD

**Issue by JoshOrndorff** [JoshOrndorff/RChain-API#5]
One can use listenForDataAtName to listen for data at public names (which we already do) as well as unforgeable names.

The unforgeable names will be harder to implement as it will require "bit tweezers" to construct the proper bit sequence to represent the unforgeable name, but we may be able to take insight from the core team once [CORE-994](https://rchain.atlassian.net/browse/CORE-994) lands.

This feature will be quite valuable for dapp developers. To, for example, check the internal state of a deployed smart contract. ([exmaple](https://github.com/JoshOrndorff/Rchain-Status/blob/master/main.js#L47-L63))

**Comment by JoshOrndorff** [comment]
Kyle Butt discussed constructing deterministic unforgeable names at RCon3
https://www.youtube.com/watch?v=RtA6hMJUP8E&list=PLf2bbiic5ZjCt_HA_wJR6_EMpxIsiSaFK&index=9

**Comment by dckc** [comment]
I watched that RCon3 talk. It was thin on examples of actually computing an unforgeable name.

Best I can tell, we'd have to port the 2 Blake512b classes from https://github.com/rchain/rchain/tree/dev/crypto/src/main/scala/coop/rchain/crypto/hash and then figure out how to use them when constructing Par objects.

**Comment by JoshOrndorff** [comment]
Will scalajs be of any use here https://www.scala-js.org/ ?

**Comment by JoshOrndorff** [comment]
Maybe a good first step would be grab an unforgeable name from the chain and confirm we can listen on it before creating our own off-chain.

**Step 1 -- Create a name, and give it away publicly**
```rholang
new private in {
  private!("try to get this text into javascript")|
  @"public"!(*private)
}
```

**Step 2 -- Get the unforgeable name in javascript**
```javascript
myNode.listenForDataAtName("public").then(private => {
  myNode.listenForDataAtNate(private).then(msg => {
    console.log(msg);
  });
});
```

**Comment by JoshOrndorff** [comment]
I've built on @crypto-coder 's work in #21 . Anyone care to give a review and merge?

**Comment by JoshOrndorff** [comment]
I think we may have actually done the important part of this. We can now construct unforgeable names from ids or read them from public names. We can listen on them once we have them. Let's open a new issue to construct them off-chain when or if we find a use case.
