### ISSUE TITLE
Another approach to connect browser to grpc?

### ISSUE THREAD

**Issue by ethanfrey** [JoshOrndorff/RChain-API#8]
I came across this project when in a similar search about 9 months ago. Maybe this also works for rchain nodes (unless they use bidirectional streaming over grpc):

https://github.com/improbable-eng/grpc-web

Great work on https://github.com/JoshOrndorff/LearnRholangByExample and making rchain programming accessible. It's helped me a lot see how to get started.

**Comment by dckc** [comment]
That would only work if
  - the RChain node's gRPC port is open to the internet
  - the RChain node is in the same origin as the relevant web page

I don't expect that to be the case in any production setting.

**Comment by JoshOrndorff** [comment]
@ethanfrey Cool project to keep an eye on, and borrow ideas from. Thanks for pointing it out and for the kind words about my rholang tutorial.

@dckc 
> the RChain node is in the same origin as the relevant web page
This may happen for popular dapps where the server that serves the UI also runs their own validator, but yeah it definitely wouldn't be the case for every dapp that someone builds.

> the RChain node's gRPC port is open to the internet
This is the case for most nodes on testnet right now.

I don't think either of those conditions on their own is particularly unlikely to be met, but I agree that having both simultaneously is unlikely. If the server for a DApp's ui has it's own node that node is probably intended for dapp-specific trafic and grpc port won't be public. On the other hand if it is a general purpose validator looking for inboud deploys it likely isn't also serving any particular dapp's ui.

In any case this isn't an "issue" with RChain-API per-se, so I'm closing.
